### ISSUE TITLE
Got an error during compilation and don't know how to fix it

### ISSUE THREAD

**Issue by bright-men** [apatra6/rhocp#1]
Got an error during compilation and don't know how to fix it.
/home/m/projects/rhocp/src/main.C: In function 'int main(int, char**)':
/home/m/projects/rhocp/src/main.C:22:31: error: 'void MooseApp::setCheckUnusedFlag(bool)' is private within this context
   22 |   app->setCheckUnusedFlag(true);
      |                               ^
In file included from /home/m/projects/rhocp/build/header_symlinks/RhocpApp.h:4,
                 from /home/m/projects/rhocp/src/main.C:1:
/home/m/projects/moose/framework/build/header_symlinks/MooseApp.h:1201:8: note: declared private here
 1201 |   void setCheckUnusedFlag(bool warn_is_error = true);
      |        ^~~~~~~~~~~~~~~~~~
make: *** [/home/m/projects/moose/framework/build.mk:145: /home/m/projects/rhocp/src/main.x86_64-conda-linux-gnu.opt.lo] Error 1
make: *** Waiting for unfinished jobs....

**Comment by apatra6** [comment]
Hi,
Which branch of MOOSE are you using? master, devel or next?
rhocp seems to be compiling fine with the MOOSE release: https://github.com/idaholab/moose/releases/tag/2022-06-10 
Can you check if this works for you?
- Anirban

**Comment by bright-men** [comment]
The version I am using is next, because it is the version I downloaded according to the installation steps given on the official website.&nbsp;I will use the version you sent to install and compile for a try. Many thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apatra6/rhocp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月4日(星期六) 中午11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apatra6/rhocp] Got an error during compilation and don't know how to fix it (Issue #1)





 
Hi,
 Which branch of MOOSE are you using? master, devel or next?
 rhocp seems to be compiling fine with the MOOSE release: https://github.com/idaholab/moose/releases/tag/2022-06-10
 Can you check if this works for you?
  
Anirban

**Comment by bright-men** [comment]
> Hi, Which branch of MOOSE are you using? master, devel or next? rhocp seems to be compiling fine with the MOOSE release: https://github.com/idaholab/moose/releases/tag/2022-06-10 Can you check if this works for you?
> 
> * Anirban

Thanks. This version can be compiled successfully. When I run  ./run_tests -j 4, the result is:
Ran 0 tests in 0.0 seconds. Average test time 0.0 seconds, maximum test time 0.0 seconds.
0 passed, 0 skipped, 0 pending, 0 failed
Is this normal？

**Comment by apatra6** [comment]
That's good to know.
We do not have any tests that can be executed with the run_tests option, so yes this is normal. This is because CPFE tests are generally much longer than conventional MOOSE tests.
You can go the examples folder and explore all the different simulation files for hcp, fcc and bcc materials.
You can find details of the constitutive model and the example simulations in this (under review) manuscript: https://www.dropbox.com/s/tleqhzfmb87cce3/rhoCP_v3_07Feb23.pdf?dl=0
- Anirban

**Comment by bright-men** [comment]
> That's good to know. We do not have any tests that can be executed with the run_tests option, so yes this is normal. This is because CPFE tests are generally much longer than conventional MOOSE tests. You can go the examples folder and explore all the different simulation files for hcp, fcc and bcc materials. You can find details of the constitutive model and the example simulations in this (under review) manuscript: https://www.dropbox.com/s/tleqhzfmb87cce3/rhoCP_v3_07Feb23.pdf?dl=0
> 
> * Anirban

Thanks, I used the given example to run and it is fine.

**Comment by apatra6** [comment]
Sounds great!
