### ISSUE TITLE
Q: should we output the corrected "F_el" in "NR_residuals" ?

### ISSUE THREAD

**Issue by Ttw0626** [apatra6/rhocp#2]
Dear rhocp-developer,

good afternoon, here is a problem or possibility which I am not totally understand.

If I am not misunderstanding:

1. the `F_el` will be corrected or updated once the `NR_residuals` is called, but `NR_residuals` just outputs the `Fp_inv` and `updated resultants`. right?
2. if there is pretty smooth of judgment for `subtimestep` and `NR_iteration` and `linear_search`, the code after converged subtimestep:
`for (unsigned int i=0; i<3; i++){`
`    for (unsigned int j=0; j<3; j++){`
`          F_el_matrix[i][j] = F_el(i,j);`
`    }`
`}`
should use final corrected or updated `F_el`, right ?

3. By the way, the `rotation matrix` at current config was updated by `F_el_matrix`, and then, the `rotated Euler angles` also was updated potentially by `F_el_matrix`, the `s` and `m` at current cofig. also.

4. should we need to calculate the updated `F_el` either inside `NR_residuals` as one of Outputs or during `linear_search` ?

Thanks
If I got any misunderstanding, please help me to figure out !

best regards,
tianwen

**Comment by apatra6** [comment]
Dear Tian Wen,

We will get back to you on these issues in a couple of days.

Thanks,
-- 
Anirban Patra
IIT Bombay

**Comment by apatra6** [comment]
In the latest commit, F_el is passed on to NR_residual by reference. This allows F_el to be updated within the NR_residual class. 

Thanks for poniting this issue!

- Anirban
