### ISSUE TITLE
Compilation Error: Potential missing argument

### ISSUE THREAD

**Issue by vprithiv** [apatra6/rhocp#3]
Hello Anirban,

Thank you for open-sourcing the code, allowing us to utilize it. While attempting to compile the rhocp using the MOOSE Next branch, I encountered the following error:

<img width="1344" alt="image" src="https://github.com/apatra6/rhocp/assets/120124981/56946b25-fddf-4d11-a913-35ad83049794">

Are we missing an argument (sys_num) for getNonlinearSystemBase() within the EBSDMeshReader.C (line 36)?

Thanks for the help,
Prithivi

**Comment by apatra6** [comment]
Hi Prithivi,

We will try to fix this in the next couple of days. In the meantime, can you check if you are getting the same error with the MOOSE master branch?

Thanks,
- Anirban

**Comment by vprithiv** [comment]
Hi Anirban,

Thanks for getting back!

I tried to build it with master branch, and I am getting the same error. I am also getting another error.

<img width="1336" alt="image" src="https://github.com/apatra6/rhocp/assets/120124981/a67074be-fdb3-45c3-a65d-b96bae6356dc">

**Comment by apatra6** [comment]
Hi Prithivi,

We have updated rhocp now to compile with the latest MOOSE master branch. Please update your moose and conda/mamba environments and then compile with the latest rhocp.

Let me know if you are still facing any issues.

- Anirban

**Comment by vprithiv** [comment]
Anirban,
Thank you for quickly fixing this. It works now.
